# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "SNT10",
  "description": "For future"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/5/
Content-Type: application/json

{
  "description": "Bedroom 2"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "id_sensor": 1,
  "temperature": 22.2
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/5/
Content-Type: application/json
