# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "SNS6",
  "description": "Underfloor"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/6/
Content-Type: application/json

{
  "description": "Underfloor bathroom"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "id_sensor": 3,
  "temperature": 20.5
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
